version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/zip/
    overwrite: yes

permission:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: before-install.sh
    - timeout: 60
      runas: root

  AfterInstall:
    - location: after-install.sh
    - timeout: 60
      runas: root
