name: React build flows
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main source code
        uses: actions/checkout@main

      - name: Cache node modules
        uses: actions/cache@main
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm install

      - name: NPM build
        run: npm run build

      - name: S3 deployment
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          build s3://songrequest-frontend
