name: React build flows
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main source code
        uses: actions/checkout@main

      - name: Install dependencies
        run: npm install

      - name: NPM build
        run: npm build
